import axios from "axios"
import { BASE_URL, GeneralResponse } from "./axios-config"
import EventSource from "react-native-sse"
import { Type } from "#models"
import { Alert } from "react-native"
import { alertModal } from "../../utils/alert-modal"
import { UserDetail } from "#api"
import { navigate } from "#navigators"

export interface NotificationColumns {
  id: number
  createAt: Date
  updatedAt: Date
  title: string
  content: string
  senderName: string
  needToPush: boolean
  adAtNight: boolean
}

interface NotificationResponse extends GeneralResponse {
  clientNotifications: NotificationColumns[]
}

interface GetNotificationsResult {
  isSuccess: boolean // 성공여부
  notifications?: NotificationColumns[] // 성공시, 펫 상세정보 리스트
  reason?: string // 실패시, 실패이유
}

export interface NotificationMessage {
  title: string
  content: string
  senderName: string
  needToPush: boolean
  adAtNight: boolean
  careGiverReceiverId?: number
  clientReceiverId?: number
}

/**
 * 로그인한 유저의 모든 반려동물 정보를 읽어온다.
 * @returns {Promise<GetNotificationsResult>}
 */
// export const getNotifications = async (): Promise<GetNotificationsResult> => {
//   try {
//     const response = await axios.get<NotificationResponse>(`${BASE_URL}/notification/client`)

//     if (!response?.data.ok) {
//       console.error("/pets API 에러!!! ♦️", response?.data?.error)
//       return { isSuccess: false, reason: response?.data?.error }
//     }
//     return {
//       isSuccess: true,
//       notifications: response.data.clientNotifications,
//     }
//   } catch (error) {
//     console.error("catch 에러!!! - getNotifications", error)
//     return { isSuccess: false, reason: error }
//   }
// }

// Generated by https://quicktype.io

/**
 * 로그인 유저의 알림 푸시를 구독시킨다.
 * @param addNotification - notification store 메서드
 * @returns
 */
export const subscribeNotification = (addNotification: (value: NotificationMessage) => void) => {
  const token = axios.defaults.headers.common["x-jwt"]

  console.log("token >>>", token)

  if (!token) {
    alert("유저 정보가 존재하지 않습니다. \n로그인 후 다시 시도해주세요.")
    return
  }

  const eventSource = new EventSource(`${BASE_URL}/notification/subscribe`, {
    headers: {
      "x-jwt": token,
    },
    debug: true,
  })

  eventSource.addEventListener("open", () => {
    console.log("event open")
    alert("알림 설정이 완료되었습니다.")
  })

  eventSource.addEventListener("message", (event) => {
    console.log("New message event:", event.data)
    // const SSEMessage: {
    //   message: NotificationMessage
    // } = JSON.parse(event.data)

    const SSEMessage: {
      message: string
    } = JSON.parse(event.data)

    console.log("JSONed message >>>", SSEMessage.message)

    // 공지 알림이 새로 들어올 때마다 store에 추가
    addNotification({
      title: SSEMessage.message,
      content: "test",
      senderName: "test",
      needToPush: false,
      adAtNight: false,
    })
  })

  eventSource.addEventListener("error", (event) => {
    if (event.type === "error") {
      console.error("Connection error:", event.message)
    } else if (event.type === "exception") {
      console.error("Error:", event.message, event.error)
    }
  })

  eventSource.addEventListener("close", () => {
    alert("알림 설정이 취소되었습니다.")
  })
}

export type SSENotificationEventDataMessage = {
  adAtNight: boolean
  content: string
  needToPush: boolean
  senderName: string
  title: string
  careGiverReceiverId?: number // 존재하면, 수신자는 펫시터
  clientReceiverId?: number // 존재하면, 수신자는 보호자. 두개가 동시에 존재할 수 없음.
}
/**
 * SSE Notification 구독 클래스
 * - 케어기버와 클라이언트의 알림을 구독한다.
 * - 알림이 들어오면, Alert로 알림을 띄운다.
 * - 알림을 누르면, 해당 화면으로 이동한다.
 * - 모드 전환 혹은, 로그아웃 시, SSE 연결을 종료한다.
 */
export class NotiSSE {
  static notiSSE: EventSource | null = null

  static connect(userDetail: UserDetail, type: Type) {
    if (!axios.defaults.headers.common["x-jwt"]) {
      alertModal("유저 정보가 존재하지 않습니다.", "로그인 후 다시 시도해주세요.")
      return
    }

    this.notiSSE = new EventSource(`${BASE_URL}/notification/subscribe`, {
      headers: { "x-jwt": axios.defaults.headers.common["x-jwt"] },
      debug: true,
    })

    // SSE 연결
    this.notiSSE.addEventListener("open", () => {
      console.debug(`🤖DEBUG ${userDetail.nickname} (${type}):`, "SSE 연결 시작")
    })

    // SSE 수신
    this.notiSSE.addEventListener("message", (event) => {
      const SSEMessage = JSON.parse(event.data)

      if (SSEMessage.message === "Heartbeat") {
        console.debug(`🤖DEBUG ${userDetail.nickname} (${type}):`, SSEMessage.message)
        return
      }

      if (SSEMessage.message === "Notification connection established") {
        console.debug(`🤖DEBUG ${userDetail.nickname} (${type}):`, SSEMessage.message)
        return
      }

      const noti: SSENotificationEventDataMessage = SSEMessage?.message
      // 수신자: 펫시터
      if (noti?.careGiverReceiverId && type === Type.CARE_GIVER) {
        console.debug(`🤖DEBUG ${userDetail.nickname} (${type}):`, noti)
        Alert.alert(
          `${noti?.title}`,
          `${noti?.content}`,
          [
            { text: "닫기", style: "cancel" },
            {
              text: "확인하기",
              onPress: () => {
                //@ts-ignore
                navigate("CgBookings", { screen: "cg-booking-list-screen" })
              },
            },
          ],
          { cancelable: true },
        )
        return
      }

      // 수산자: 보호자
      if (noti?.clientReceiverId && type === Type.CLIENT) {
        console.debug(`🤖DEBUG ${userDetail.nickname} (${type}):`, noti)
        Alert.alert(
          `${noti?.title}`,
          `${noti?.content}`,
          [
            { text: "닫기", style: "cancel" },
            {
              text: "확인하기",
              onPress: () => {
                //@ts-ignore
                navigate("Bookings")
              },
            },
          ],
          { cancelable: true },
        )
        return
      }

      if (!noti?.careGiverReceiverId && !noti?.clientReceiverId) {
        console.debug(`🤖DEBUG ${userDetail.nickname} (${type}):`, "🐞")
        console.debug(`🤖DEBUG ${userDetail.nickname} (${type}):`, noti)
      }
    })
  }

  // 로그아웃 시 (= AllTabs 컴포넌트가 unmount 될 때)
  // eventSource.close() 호출 (= SSE 연결 종료)
  static disconnect(userDetail, type) {
    // SSE 연결 종료
    if (this.notiSSE) {
      this.notiSSE.close()
      this.notiSSE = null
      console.debug(`🤖DEBUG ${userDetail.nickname} (${type}):`, "SSE 연결 종료")
    }

    //! 이걸로하면 연결 종료가 안됨. 왜지?
    // this.notiSSE.addEventListener("close", () => {
    //   console.log(`[SSE Close event] ${type}`)
    // })
  }
}
