//! 항상 이미지 파일명은 언더바 (_) 로 작성한다
const IMAGES = {
  arrow_down: require("../common-images/arrow_down.png"),
  arrow_up: require("../common-images/arrow_up.png"),
  bell: require("../common-images/bell.png"),
  calendar: require("../common-images/calendar.png"),
  care_giver_logo_162x20: require("../common-images/care_giver_logo_162x20.png"),
  certificate_badge: require("../common-images/certificate_badge.png"),
  default_pet_image_60: require("../common-images/default_pet_image_60.png"),
  default_profile_image_comment: require("../common-images/default_profile_image_comment.png"),
  deselect_checkbox: require("../common-images/deselect_checkbox.png"),
  empty_12: require("../common-images/empty_12.png"),
  empty_heart: require("../common-images/empty_heart.png"),
  go_back: require("../common-images/go_back.png"),
  gps: require("../common-images/gps.png"),
  in_progress_booking_background: require("../common-images/in_progress_booking_background.png"),
  list_bars: require("../common-images/list_bars.png"),
  location: require("../common-images/location.png"),
  more_info: require("../common-images/more_info.png"),
  profile_default: require("../common-images/profile_default.png"),
  rating_star: require("../common-images/rating_star.png"),
  rating_star_empty: require("../common-images/rating_star_empty.png"),
  rating_star_half: require("../common-images/rating_star_half.png"),
  right_arrow_grey: require("../common-images/right_arrow_grey.png"),
  right_arrow_navy: require("../common-images/right_arrow_navy.png"),
  search: require("../common-images/search.png"),
  select_checkbox: require("../common-images/select_checkbox.png"),
  three_dots: require("../common-images/three_dots.png"),
  timer: require("../common-images/timer.png"),
  vertical_3_dots: require("../common-images/vertical_3_dots.png"),
  write_comment: require("../common-images/write_comment.png"),
  x_grey: require("../common-images/x_grey.png"),
}

//! 예외적으로 export default 허용 
export default IMAGES
