name: Build Ios Test

on:
  push:
    branches: [test/CICD-hojung]

jobs:
  build:
    name: iOS Build Test
    runs-on: macOS-latest

    steps:
      - name: Show self-hosted machine infomation
        run: uname -a

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo from test/CICD-hojung branch
        uses: actions/checkout@v3
        with:
          ref: test/CICD-hojung

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependency
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Install pod dependency
        run: |
          cd ios && pod install --repo-update --clean-install

      - name: Select Xcode 14.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3.1"

      - name: Build iOS (Release)
        uses: yukiarrr/ios-build-action@v1.11.2
        with:
          project-path: ios/CareGiver.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: "Apple Distribution"
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          workspace-path: ios/CareGiver.xcworkspace
          output-path: "CareGiver.ipa"
